# Generated by Django 5.2.7 on 2025-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, verbose_name='課號'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=100, verbose_name='任課老師'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='課名'),
        ),
    ]
